/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DuckTiersBasicInterface extends ethers.utils.Interface {
  functions: {
    "getUserTier(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getUserTier", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getUserTier",
    data: BytesLike
  ): Result;

  events: {};
}

export class DuckTiersBasic extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DuckTiersBasicInterface;

  functions: {
    getUserTier(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "getUserTier(address)"(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;
  };

  getUserTier(_userAddress: string, overrides?: CallOverrides): Promise<number>;

  "getUserTier(address)"(
    _userAddress: string,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    getUserTier(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;

    "getUserTier(address)"(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    getUserTier(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserTier(address)"(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getUserTier(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserTier(address)"(
      _userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
